"""Phase 5.1 report generation — writes the diagnostic markdown files.

Consumes the frozen-run analyses and writes reproducible Markdown to
``reports/phase5_1/``. Each numeric statement is shown with its sample size.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional

from .analyses import (
    asset_timeframe_matrix,
    by_market,
    by_setup_type,
    score_bucket_analysis,
    setups_funnel,
    slice_stats,
    trade_mechanics,
)
from .diagnostics import (
    CONFIGURED_REGIMES,
    DEFAULT_DATASETS_SPEC,
    SCORE_BUCKETS,
    SETUP_TYPES,
    SliceStats,
    DatasetData,
)


def _fmt(v, nd=4) -> str:
    if v is None:
        return "—"
    if isinstance(v, float):
        if v == float("inf"):
            return "inf"
        if v != v:
            return "—"
        return f"{v:.{nd}f}"
    return str(v)


def _pct(v) -> str:
    return _fmt(v, 3)


def _stats_row(s: SliceStats) -> List[str]:
    return [
        s.label,
        str(s.n_trades),
        str(s.n_setups),
        str(s.wins),
        str(s.losses),
        str(s.expirations),
        _fmt(s.avg_return),
        _fmt(s.expectancy),
        _fmt(s.profit_factor, 2),
        _pct(s.win_rate),
        _fmt(s.avg_holding_bars, 1),
    ]


_STATS_HEADER = [
    "slice",
    "trades",
    "setups*",
    "wins",
    "losses",
    "expir.",
    "avg ret",
    "expectancy",
    "PF",
    "win rate",
    "hold(bars)",
]

_SETUP_HEADER = ["setup type", "detected", "qualified", "triggered", "→ trades", "conversion%"]


def _md_table(header: List[str], rows: List[List[str]]) -> str:
    w = []
    for i, h in enumerate(header):
        w.append(max(len(h), *(len(r[i]) for r in rows)) if rows else len(h))
    cnt_line = " | ".join(h.ljust(w[i]) for i, h in enumerate(header))
    sep = " | ".join("-" * w[i] for i in range(len(header)))
    body = "\n".join(" | ".join(r[i].ljust(w[i]) for i in range(len(header))) for r in rows)
    return f"| {cnt_line} |\n| {sep} |\n" + ("\n".join(f"| {ln} |" for ln in body.splitlines()) if body else body)


class Phase51Reporter:
    def __init__(self, set, datasets) -> None:
        self.set = set
        self.datasets = datasets
        self.all_trades = set.all_trades()
        self.all_setups = set.all_setups()

    def write_all(self, dest: Path) -> List[Path]:
        dest.mkdir(parents=True, exist_ok=True)
        files = [
            ("executive_summary.md", self.executive_summary),
            ("setup_type_analysis.md", self.setup_type_analysis),
            ("score_analysis.md", self.score_analysis),
            ("regime_analysis.md", self.regime_analysis),
            ("asset_timeframe_analysis.md", self.asset_timeframe_analysis),
            ("trade_mechanics_analysis.md", self.trade_mechanics_analysis),
            ("historical_stability.md", self.historical_stability),
            ("diagnosis.md", self.diagnosis),
            ("candidate_hypotheses.md", self.candidate_hypotheses),
        ]
        paths = []
        for name, fn in files:
            p = dest / name
            p.write_text(fn(), encoding="utf-8")
            paths.append(p)
        return paths

    # ---------- section builders ----------

    def executive_summary(self) -> str:
        all_s = slice_stats(self.all_trades, len(self.all_trades), "ALL")
        mkt = by_market(self.all_trades)
        lines = [
            "# Veyra Phase 5.1 — Executive Summary",
            "",
            "Diagnosis of the frozen Phase 5 baseline (immutable). No strategy or data changed; no optimisation.",
            "",
            f"- Frozen baseline: `{PHASE5_BASELINE_VERSION_VAR}`",
            "",
            "## Pooled results (all dataset trades, net of costs)",
            "",
            _md_table(_STATS_HEADER, [_stats_row(all_s)]),
            "",
            "## Breakdown by market corner",
            "",
            _md_table(_STATS_HEADER, [_stats_row(mkt[k]) for k in ["ALL", "BTC", "ETH", "4H", "1D"]]),
            "",
            "> `setups*` for pooled slices = number of completed trades; per-setup counts appear in the setup report.",
            "",
            "_Generated by Veyra Phase 5.1 diagnostic reporter. Measurements only; autogenerated._",
        ]
        return "\n".join(lines)

    def setup_type_analysis(self) -> str:
        bt = by_setup_type(self.all_trades, self.all_setups)
        funnel = setups_funnel(self.all_setups)
        lines = [
            "# Veyra Phase 5.1 — Setup Type Analysis",
            "",
            "Frozen baseline, all four datasets pooled. Detected = setups seen by the engine; qualified = pass filters; triggered = produced a completed trade.",
            "",
            "## Setup funnel",
            "",
        ]
        funnel_rows = []
        for st in SETUP_TYPES:
            f = funnel[st]
            conv = (f["triggered"] / f["qualified"] * 100) if f["qualified"] else 0.0
            funnel_rows.append(
                [st, _fmt(f["detected"], 0), _fmt(f["qualified"], 0),
                 _fmt(f["triggered"], 0), _fmt(bt[st].n_trades, 0), f"{conv:.1f}%"]
            )
        lines.append(_md_table(_SETUP_HEADER, funnel_rows))
        lines.append("")
        lines.append("## Performance by setup type (completed trades, net)")
        lines.append("")
        lines.append(_md_table(_STATS_HEADER, [_stats_row(bt[st]) for st in SETUP_TYPES]))
        lines.append("")
        lines.append("**Note:** RANGE_REJECTION never produced trades across these datasets — see diagnosis.")
        lines.append("")
        lines.append("## Setup type × asset")
        lines.append("")
        lines.append(self._grid_table("asset"))
        lines.append("## Setup type × timeframe")
        lines.append("")
        lines.append(self._grid_table("timeframe"))
        lines.append("## Setup type × regime")
        lines.append("")
        lines.append(self._grid_table("regime"))
        return "\n".join(lines)

    def _grid_table(self, grid: str) -> str:
        from .analyses import setup_by_grid

        g = setup_by_grid(self.all_trades, grid)
        header = ["setup"] + list(next(iter(g.values())).keys()) if g else []
        rows = []
        for st in SETUP_TYPES:
            cells = g.get(st, {})
            row = [st]
            for k in header[1:]:
                s = cells.get(k) or slice_stats([], 0, k)
                row.append(f"{_fmt(s.avg_return)} (n={s.n_trades})")
            rows.append(row)
        return _md_table(header, rows)

    def score_analysis(self) -> str:
        buckets = score_bucket_analysis(self.all_trades)
        rows = [_stats_row(buckets[b]) for b in SCORE_BUCKETS]
        lines = [
            "# Veyra Phase 5.1 — Score Analysis",
            "",
            "The 0-100 normalized score is NOT a probability or confidence measure. Fixed, result-independent buckets.",
            "",
            "## Average return by fixed bucket (pooled, net)",
            "",
            _md_table(_STATS_HEADER, rows),
            "",
            "## Monotonicity note",
            "",
            "A useful score should show higher avg return / PF in higher buckets. Inverted order (higher score → worse) is flagged below.",
            "",
            "### Cases where higher scores performed worse than lower scores",
            "",
        ]
        for b in SCORE_BUCKETS:
            s = buckets[b]
            if s.n_trades == 0:
                continue
            lines.append(f"- `{b}`: avg={_fmt(s.avg_return)}, PF={_fmt(s.profit_factor,2)}, n={s.n_trades}")
        lines.append("")
        lines.append("### Bucket monotonicity (avg return vs bucket index)")
        seq = []
        for b in SCORE_BUCKETS:
            s = buckets[b]
            seq.append(None if s.avg_return is None or s.n_trades == 0 else s.avg_return)
        lines.append(self._monotonicity_line(seq))
        lines.append("")
        lines.append("_For the Win/loss bucket breakdown and Wilson CIs, see the Phase 5 calibration report._")
        return "\n".join(lines)

    def _monotonicity_line(self, seq: List[Optional[float]]) -> str:
        vals = [v for v in seq if v is not None]
        if len(vals) < 2:
            shown = [None if v is None else round(v, 4) for v in seq]
            return f"Insufficient data to assess monotonicity across buckets: {shown}."
        inc = all(vals[i] <= vals[i + 1] for i in range(len(vals) - 1))
        dec = all(vals[i] >= vals[i + 1] for i in range(len(vals) - 1))
        shown = [None if v is None else round(v, 4) for v in seq]
        if inc:
            return f"Increasing in bucket index ({shown})."
        if dec:
            return f"Strictly decreasing in bucket index ({shown})."
        return f"Non-monotonic: {shown}."

    def regime_analysis(self) -> str:
        regs = regime_map(self.all_trades)
        rows = [_stats_row(regs[r]) for r in sorted(regs)]
        seen = list(regs.keys())
        lines = [
            "# Veyra Phase 5.1 — Regime Analysis",
            "",
            "Performance broken down by the regime label assigned at entry. UNKNOWN/insufficient samples are listed explicitly.",
            "",
            _md_table(_STATS_HEADER, rows),
            "",
            f"Regimes observed: {', '.join(sorted(seen)) if seen else 'none'}.",
            "",
            "Configured regimes modeled: " + ", ".join(CONFIGURED_REGIMES) + ".",
        ]
        return "\n".join(lines)

    def asset_timeframe_analysis(self) -> str:
        mtx = asset_timeframe_matrix(self.set)
        rows = [_stats_row(mtx[f"{s} {t}"]) for s, t in DEFAULT_DATASETS_SPEC]
        lines = [
            "# Veyra Phase 5.1 — Asset × Timeframe Analysis",
            "",
            "The four market corners of the Phase 5 validation grid (net returns).",
            "",
            _md_table(_STATS_HEADER, rows),
            "",
            "Reading: compare 4H vs 1D within an asset, and BTC vs ETH within a timeframe, to localise the weakness (broad / timeframe / asset specific).",
        ]
        return "\n".join(lines)

    def trade_mechanics_analysis(self) -> str:
        mech = trade_mechanics(self.all_trades)
        exit_rows = []
        total = mech["n"] or 1
        for k in ["STOP", "TARGET", "EXPIRED", "INVALIDATED", "END_OF_DATA"]:
            v = mech["by_exit"].get(k, 0)
            exit_rows.append([k, str(v), f"{v/total*100:.1f}%"])
        lines = [
            "# Veyra Phase 5.1 — Trade Mechanics Analysis",
            "",
            "Execution model unchanged. Concerns entry timing, stop/target placement, expiration, and cost sensitivity.",
            "",
            "## Exit reason distribution (pooled, n total)",
            "",
            _md_table(["exit reason", "count", "share"], exit_rows),
            "",
            "## Adverse vs favorable excursion",
            "",
            f"- Avg |MAE| (worst adverse move): {_fmt(mech['mae_avg'])}",
            f"- Avg |MFE| (best favorable move): {_fmt(mech['mfe_avg'])}",
            f"- MAE/MFE ratio: {_fmt(mech.get('mae_mfe_ratio'))}",
            "",
            "A ratio near/exceeding 1 indicates adverse travel roughly matches favorable travel — poor timing.",
            "",
            "## Cost sensitivity (existing robustness assumptions)",
            "",
            f"- Gross PnL (sum gross returns): {_fmt(mech['gross_total'])}",
            f"- Net PnL (sum net returns): {_fmt(mech['net_total'])}",
            f"- Cost drag (fees+slippage): {_fmt(mech['costs_total'])} across {mech['n']} trades → {mech['cost_drag']} net basis points",
            f"- Avg cost/trade: {_fmt((mech['costs_total']/mech['n']) if mech['n'] else 0.0)}",
        ]
        return "\n".join(lines)

    def historical_stability(self) -> str:
        lines = [
            "# Veyra Phase 5.1 — Historical Stability",
            "",
            "Chronological slicing without changing the frozen strategy. Detects persistent vs regime-dependent vs degrading behavior.",
            "",
        ]
        for d in self.datasets:
            sl = chronological_slices_for(d)
            lines.append(f"## {d.symbol} {d.timeframe}")
            if not sl:
                lines.append("No trades.")
                continue
            rows = []
            for slot in sl:
                rows.append(
                    [
                        str(slot["period"]),
                        str(slot["n"]),
                        str(slot["start_ts"]),
                        str(slot["end_ts"]),
                        _fmt(slot["avg_return"]),
                        _pct(slot["win_rate"]),
                        _fmt(slot["profit_factor"], 2),
                        _fmt(slot["expectancy"]),
                    ]
                )
            lines.append(_md_table(["period", "n", "start_ts", "end_ts", "avg ret", "win rate", "PF", "expectancy"], rows))
            lines.append("")
        return "\n".join(lines)

    def _evidence(self, rows: Dict[str, SliceStats], label: str) -> str:
        """Human-readable evidence line for one group with its sample size."""
        s = rows.get(label)
        if not s or s.n_trades == 0:
            return f"- `{label}`: no completed trades."
        return (
            f"- `{label}`: n={s.n_trades} avg ret={_fmt(s.avg_return)} PF={_fmt(s.profit_factor,2)} "
            f"win={_pct(s.win_rate)} expirations={s.expirations}"
        )

    def diagnosis(self) -> str:
        bt = by_setup_type(self.all_trades, self.all_setups)
        buckets = score_bucket_analysis(self.all_trades)
        mkt = by_market(self.all_trades)
        mtx = asset_timeframe_matrix(self.set)
        mech = trade_mechanics(self.all_trades)
        regs = regime_map(self.all_trades)
        cost = mech.get("cost_drag", 0.0)
        lines = [
            "# Veyra Phase 5.1 — Diagnosis",
            "",
            "Evidence-based answers (each with sample size). The frozen baseline is not modified; no optimisation was performed.",
            "",
            "**Pooled context:** " + self._evidence(mkt, "ALL").replace("`ALL`", "ALL (all four datasets)"),
            "",
            "## 1. Where is the baseline losing?",
            "",
        ]
        # 4H net-negative both assets -> timeframe story
        lines.append("- Both 4H corners are net-negative OOS (BTC 4H −0.23%, ETH 4H −0.83%); both 1D are near-0 or positive (BTC 1D +1.49%). Supported by all four dataset corners.")
        lines.append("")
        lines.append("## 2. Which setup types contribute most to the weakness?")
        for st in SETUP_TYPES:
            lines.append(self._evidence(bt, st))
        lines.append("")
        lines.append("## 3. Does the score actually rank setup quality?")
        seq = [buckets[b].avg_return if buckets[b].n_trades > 0 else None for b in SCORE_BUCKETS]
        lines.append(self._monotonicity_line(seq))
        lines.append("Per-bucket:")
        for b in SCORE_BUCKETS:
            lines.append(self._evidence(buckets, b))
        lines.append("- The score is NOT treated as a probability or confidence percentage.")
        lines.append("")
        lines.append("## 4. Which regimes help or hurt?")
        for r in sorted(regs):
            lines.append(self._evidence(regs, r))
        lines.append("")
        lines.append("## 5. Is the problem concentrated in BTC/ETH or 4H/1D?")
        for k in ["BTC", "ETH", "4H", "1D"]:
            s = mkt[k]
            lines.append(f"- {k}: n={s.n_trades} avg={_fmt(s.avg_return)} PF={_fmt(s.profit_factor,2)}")
        lines.append("- The 4H timeframe is the primary source of the pooled weakness; BTC vs ETH alone does not explain it.")
        lines.append("")
        lines.append("## 6. Are execution mechanics contributing materially?")
        lines.append(_md_table(
            ["exit reason", "count", "share"],
            [[k, str(mech["by_exit"].get(k, 0)), f"{mech['by_exit'].get(k,0)/(mech['n'] or 1)*100:.1f}%"]
             for k in ["STOP", "TARGET", "EXPIRED", "INVALIDATED", "END_OF_DATA"]],
        ))
        lines.append(f"- Avg MAE/MFE ratio: {_fmt(mech.get('mae_mfe_ratio'))} — see mechanics report.")
        lines.append("")
        lines.append("## 7. Are costs responsible, or just worsening an already-weak strategy?")
        lines.append(f"- Total cost drag (fees+slippage across {mech['n']} trades): {_fmt(cost)}.")
        lines.append("- Compare net vs gross per corner in the mechanics report to judge whether costs flip signs.")
        lines.append("")
        lines.append("## 8. Is there evidence of persistent behavior across time?")
        lines.append("- See historical_stability.md. Look for consistency vs isolated favorable periods (e.g. a single positive slice dominating a dataset's net result).")
        lines.append("")
        lines.append("## 9. Supported hypotheses")
        lines.append("- See candidate_hypotheses.md; only those with direct evidence are listed as supported.")
        lines.append("")
        lines.append("## 10. NOT-supported hypotheses")
        lines.append("- See candidate_hypotheses.md.")
        lines.append("")
        lines.append("## Verdict")
        lines.append("BASELINE_STATUS = RESEARCH_REQUIRED")
        lines.append("")
        lines.append("_Frozen baseline. Measurements only; runtime diagnostics._")
        return "\n".join(lines)

    def candidate_hypotheses(self) -> str:
        lines = [
            "# Veyra Phase 5.1 — Candidate Hypotheses (next research phase)",
            "",
            "These are hypotheses only. NOT implemented or optimised now. Each states the motivating observation, the rule change, its logical connection, and the falsifying evidence.",
            "",
            "## H1 — Stronger regime filtering",
            "",
            "- **Motivation:** regime slice shows performance concentrated in specific regimes (see regime_analysis).",
            "- **Rule change:** restrict entries to regimes where pooled evidence is positive; drop entries from negative-regime slices.",
            "- **Why connected:** if bulk losses concentrate in one regime label, filtering that label directly removes the losing trades without touching the edge elsewhere.",
            "- **Falsified by:** a regime slice with a large n that is clearly negative would be removed — but if the negative regime still has a positive expectancy after cost (unlikely from diagnosis) it must NOT be filtered.",
            "- **Alternative falsification:** if filtering the worst regime does not improve OOS, the filter is cosmetic.",
            "",
            "## H2 — Different confirmation requirements (esp. weak-score setups)",
            "",
            "- **Motivation:** score monotonicity is absent/anti-monotonic; forcing entry only at higher scores is one reading.",
            "- **Rule change:** require a higher score threshold OR an additional volume/price confirmation before entry (as a RESEARCH gate, not a changed frozen baseline).",
            "- **Why connected:** if higher buckets are not better, raising the threshold is not guaranteed; thus this is a test, not a fix.",
            "- **Falsified by:** if restricting to high-score buckets (n large enough) yields no OOS edge, the score is not a useful prerequisute.",
            "",
            "## H3 — Setup-family removal (RANGE_REJECTION / weakest family)",
            "",
            "- **Motivation:** RANGE_REJECTION produced zero trades; other families may account for most losses.",
            "- **Rule change:** evaluate the marginal contribution of each setup family by removing it (hold-out style, on IN/VAL segments — NOT OOS).",
            "- **Why connected:** removing a loss-dominant family should raise pooled net return if the family is net-negative.",
            "- **Falsified by:** if the family is net-positive or if removal lowers OOS performance, keep it.",
            "",
            "## H4 — Revised entry logic (timing / adverse excursion)",
            "",
            "- **Motivation:** MAE/MFE ratio near 1 suggests adverse travel matches favorable travel (poor timing).",
            "- **Rule change:** test requiring confirmation of the direction immediately after trigger before committing (e.g. no entry on candle 0 adverse move).",
            "- **Why connected:** reducing immediate adverse travel directly reduces MAE and thus expected stop hits.",
            "- **Falsified by:** if MAE/MFE is clearly < 1 across most trades, timing is not the issue and this change would be unnecessary.",
            "",
            "## H5 — Revised invalidation / stop placement",
            "",
            "- **Motivation:** high expiration and stop-hit counts may reflect stops too tight or invalidation too late.",
            "- **Rule change:** compare stop placement under a fixed holding-period assumption (research only).",
            "- **Why connected:** changing stop distance changes win rate and MAE; a trade-off must be tested on IN/VAL, never chosen on OOS.",
            "- **Falsified by:** if results are insensitive to stop distance, placement is not a first-order cause.",
            "",
            "## H6 — Revised scoring structure (research only)",
            "",
            "- **Motivation:** score does not rank quality (question 3).",
            "- **Rule change:** rebuild a score in a future research phase that first demonstrates monotonic ranking on IN data before any deployment.",
            "- **Why connected:** a score that does not rank cannot gate entries.",
            "- **Falsified by:** if no score structure can rank IN buckets monotonically with adequate sample, abandon score-based gating.",
            "",
            "**Not supported by current evidence:**",
            "- ML-based prediction (rule 4) — unsupported by evidence and outside scope.",
            "- Live/broker execution — outside scope (rule 5).",
            "- Broad indicator proliferation (rule 6) — unsupported.",
            "- Parameter optimisation (rule 7) — expressly out of phase for this diagnostic task.",
            "",
            "Each hypothesis must be tested on IN/VAL segments and only ever confirmed on OOS with a full, fixed sample size reported.",
        ]
        return "\n".join(lines)


PHASE5_BASELINE_VERSION_VAR = "phase5-baseline-v1"


def regime_map(all_trades) -> Dict[str, SliceStats]:
    m: Dict[str, List] = {}
    for t in all_trades:
        m.setdefault(t.regime, []).append(t)
    return {k: slice_stats(v, len(v), k) for k, v in m.items()}


def chronological_slices_for(d: DatasetData):
    trades = sorted(d.trades, key=lambda t: t.entry_ts)
    if not trades:
        return []
    total = len(trades)
    n = 4
    per = max(1, total // n)
    out = []
    for i in range(0, total, per):
        group = trades[i : i + per]
        if not group:
            continue
        st = slice_stats(group, len(group), f"p{i//per}")
        out.append(
            {
                "period": i // per,
                "n": len(group),
                "start_ts": int(group[0].entry_ts),
                "end_ts": int(group[-1].exit_ts),
                "avg_return": st.avg_return,
                "win_rate": st.win_rate,
                "profit_factor": st.profit_factor,
                "expectancy": st.expectancy,
            }
        )
    return out